spring.application.name=mailsender

# RabbitMQ Listener Control (Anti-Spam / Rate Limiting)
# Processa 2 e-mails por vez, no máximo 5 em paralelo.
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=5
# Garante que o consumidor pegue apenas 1 mensagem por vez do broker
spring.rabbitmq.listener.simple.prefetch=1

# RABBITMQ
spring.rabbitmq.host=10.115.6.76
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123admin

# MinIO / S3 Configuration
minio.endpoint=http://10.115.7.79:9900
minio.access-key=mailsender-key
minio.secret-key=4ZXsempS58NvO4yVcrTaf4xIqkx3QQTVakE2J7WV

# Spring Mail (Exemplo para Mailtrap/SMTP local)
spring.mail.host=10.117.2.204
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mailsender_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Console (Disabled for Postgres)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
